### ISSUE TITLE
Add GitHub Actions workflow for SCSS compilation with CSS variables

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-theme-quark#1]
Create a GitHub Actions workflow to compile SCSS files to CSS, converting SCSS variables to CSS custom properties (variables).

### Requirements
- Set up a GitHub Actions workflow to:
  - Compile SCSS files to CSS
  - Maintain the same directory structure in output
  - Convert SCSS variables to CSS custom properties
  - Use "expanded" output style for better readability
  - Package the compiled CSS files into an archive

### Technical Specifications
1. The workflow should:
   - Trigger on relevant events (push, pull request)
   - Use a Node.js environment
   - Install required dependencies (sass, postcss, postcss-cli)
   - Process SCSS files maintaining directory structure
   - Create an archive of the compiled CSS files

2. SCSS Processing Requirements:
   - Convert `$variable` syntax to `--variable` CSS custom properties
   - Maintain variable definitions in `:root` scope
   - Preserve imports and file relationships
   - Use expanded output style for better readability

### Example Transformation
Input SCSS:
```scss
$primary-color: #0074D9;

body {
    background-color: $primary-color;
}
```

Expected CSS Output:
```css
:root {
    --primary-color: #0074D9;
}

body {
    background-color: var(--primary-color);
}
```

### Implementation Notes
- Consider using PostCSS plugins for variable conversion
- Ensure proper error handling and reporting
- Add appropriate status checks
- Include workflow status badge in README.md
